# Generated by Django 2.1.2 on 2018-11-01 13:21

import accounts.validators
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Area')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Area ar')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'professionals_area',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Feature')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Feature ar')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'professionals_feature',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_ar', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'professionals_item',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Job')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Job ar')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'professionals_job',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_menu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'professionals_menu',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_menu_items', to='professionals.Item')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='professionals.Menu')),
            ],
            options={
                'verbose_name': 'MenuItem',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'professionals_menu_item',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('about', models.TextField(max_length=255, verbose_name='About')),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[accounts.validators.phone_number_validator])),
                ('call_time_from', models.TimeField(blank=True, null=True)),
                ('call_time_to', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('slug', models.SlugField(max_length=255)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_users', to='professionals.Area')),
                ('features', models.ManyToManyField(blank=True, related_name='feature_users', to='professionals.Feature')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_users', to='professionals.Job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'professionals_profile',
            },
        ),
        migrations.CreateModel(
            name='SocialWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, validators=[accounts.validators.facebook_validator], verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, validators=[accounts.validators.twitter_validator], verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, validators=[accounts.validators.instagram_validator], verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, null=True, validators=[accounts.validators.youtube_validator], verbose_name='Youtube')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_social_websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Website',
                'verbose_name_plural': 'Social Websites',
                'db_table': 'professionals_social_website',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_items', to='professionals.Job'),
        ),
    ]
